### ISSUE TITLE
Develop staking & withdraw timelock

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#14]
During development of tests (https://github.com/DMDcoin/hbbft-posdao-contracts/issues/12), this requirement has been commented out.
contracts/base/StakingHbbftBase.sol:980

including the test "should fail if stacking time is inside disallowed range"

test/StakingHbbft.js:184

It's was not well implemented and the problem  evm_increaseTime  doesn't help at all.
https://github.com/DMDcoin/hbbft-posdao-contracts/issues/13

see checkin: 0688700b2f68e79f0b4a31d5fbee057996fe4ed8

**Comment by SurfingNerd** [comment]
POSDAO Whitepaper describes:
```
The ​ StakingAuRa.stake​ and ​ StakingAuRa.addPool​ functions can only be called if the
StakingAuRa.areStakeAndWithdrawAllowed​ getter returns ​ true . ​ This getter defines the
window inside the staking epoch, during which staking and withdrawing can be performed by
the participants. For AuRa, this window begins from the first block of a staking epoch and ends
during the final blocks of the staking epoch when a disallow period begins (the disallow period
duration is defined by ​ StakingAuRa.stakeWithdrawDisallowPeriod​ ).
```
It would be good to figure out the incentivation and the impacts for this decision. 
see checkin: 36223ecab018404b97e86ad14e7660a72707671f (solved by increasing the wait time to 4 seconds instead of 2 in the test)
see checkin:  d6cc9631f95dae635705ad2ccd6a559a7f27c7ba This checkin removed this constrained completly - introducing NO general timelock for satking and withdraw at all.
The removal of the general timelock solved about 12 tests that failed before.

Maybe the incentive was, that Funds that got staked on nodes, and those nodes did not get selected, that those funds get locked as well ?!

**Comment by cryptonit** [comment]
afaik there is no need to lock dpos staking as rewards calculated at end of epoch. and stake that is moved effective only count for next epoch. a new stake is not active before a new epoch starts

this rukesets are enough 

u dont want to move stake away from a active validator as u wont get rewards for actual epoch

u dont be able stake on top of a active validator as ur stake goeas active next epoch and u cant predict he is active again then

u have to see that there in fact are two operations

unstake and stake

u can unstake any time it getactive instant
u xan stake anytime but it gets active at next epoch

**Comment by cryptonit** [comment]
regatding the 2 operations unstake and stake
from usability oetspective we need to implement

a move stake operation so user dont have to go twice through dapp and password and so on and both operations can be combined

so as a user i want to be able to
fresh stake
unstake and have coins again on my adress
move which allow unstake and at same operation stake on another validator (still the stake not active before next epoch starts)

**Comment by SurfingNerd** [comment]
after removing this constrained, i removed also the test that verified this feaure:
c013d01df4ca9ea90ff7e157fef5fb3f949f297e

**Comment by SurfingNerd** [comment]
A increased timelock for the staking collateral could also act as a protection against malicious actors that abuse the possibility to create multiple nodes that abuse the free service transactions.
