### ISSUE TITLE
Diamond Bonus Score system

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#171]
# Diamond Bonus Score

### assumed network parameters in the examples:
stakingFixedEpochDuration: 43200 

### boundaries
ScoreMinimum: 1
ScoreMaximum: 1000

### Positive Scores 
StandbyBonus: 15

### Negative Scores:
NoKeyWrite: 100
MaxBadPerformanceScore: 100
NoStandbyPenalty: 15 (Same value as StandbyBonus)

## During the epoch penalties
If a Node lost connectivity, based on the connectivity tracker rules (2 / 3 Consensus), it automatically looses 1 Point every (`stakingFixedEpochDuration()` / `MaxBadPerformanceScore` =  43200 / 100  = 432 seconds = 7,2 minutes.
- [ ] Calculate on reportMissingConnectivity()
- [ ] Calculate on reportReconnect()

At the beginning of the `epoch end` we give out Penalty Scores for Nodes depending on their performance:
every Node receives a `BadPerformanceScore` penalty if they are still unavailable, with the same rules defined in `During the Epoch`.

## Stand by bonus
 
- [ ] Calculates after validator confirmation of new validator set.
- [ ] every Node that did not manage to get into the validator set and was online (flagged as available) receives the `StandbyBonus`, according to the length of the last epoch (100% for the full `stakingFixedEpochDuration()` )
1 point for every   `stakingFixedEpochDuration()`/ `StandbyBonus`= 2880 seconds = 48 minutes.
Every Node that was not available receives the same amount as negative score.

## Keygen Phase:
- [ ] every Node that did not write their PARTS or ACKS receive a penalty of `NoKeyWrite`

## Likelihood:
- [ ] The Likelihood of a Validator Candidate is adjusted every time the Bonus Score changes. The Bonus Score act's as a multiplier.  A Validator with Max Bonus Score has 1000 times the likelihood of a Node with the same Stake at minimum Bonus score.

## Dao Value Guards
- [ ] define possible values

## Spec Generation
- [ ] update spec generation

**Comment by cryptonit** [comment]
minimum score 1 

1000 scoree means full posdao chance  1000/1000 (based on staked coins)
1 scoree means 1/1000 of the full posdao chance to come into the set
everything between proportional between......

**Comment by SurfingNerd** [comment]
done so far, we will handle change request as new issues,
