### ISSUE TITLE
Feature Request: no payout in the first weeks

### ISSUE THREAD

**Issue by SurfingNerd** [DMDcoin/diamond-contracts-core#212]
according to the design, the blockchain should start without a payout in the first weeks, until enough validators got onboard.

with the latest changes, that are still in development, the DAO is not able to do so, because the reward fractions are not votable anymore.

furthermore, in the current design we would run in a "divide by zero" situation, if we want to define a 0 Payout.

**Comment by cryptonit** [comment]
we make it simple the dao governance share is 90% and not 10% the first 20 epochs (thats 10% instead of 90% for the first 10 days for the validators)

thats a so called soft startup to give people 10 days time set up validators

**Comment by SurfingNerd** [comment]
oh my bad, i forgot we have already a solution.
the payout begins once the pods are fed up,

so we can delay the filling of the reinsert & delta pot
