### ISSUE TITLE
Make ValueGuards contract upgrade-safe

### ISSUE THREAD

**Issue by axel-muller** [DMDcoin/diamond-contracts-core#265]
ValueGuards contract is currently used as base in inheritance chain in 4 core contracts. Existing implementation does not support safe storage extension during upgrades. This will limit us in the future if we need to extend ValueGuards. 

To make ValueGuards upgrade safe we should use [ERC-7201](https://eips.ethereum.org/EIPS/eip-7201) standard. Usage example may be found in [openzeppelin contracts](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/token/ERC20/ERC20Upgradeable.sol).

**Comment by MSalman6** [comment]
Added ValueGuardsV2 in #264 with namespace storage layout making it upgrade-safe, though we need to cleanup/replace v1
